const fs = require("fs");
const os = require("os");
const path = require("path");

// Integration: a token generated by channels.a2a.peer-upsert lands in
// AlphaClaw's real .env store and reaches the gateway child env built by the
// real gatewayEnv() — through the built-in allowlist, not the deployment-only
// ALPHACLAW_GATEWAY_ENV_PASSTHROUGH hatch. Same temp-root idiom as
// gateway-env-allowlist.test.js: the root is fixed BEFORE constants load.
const kTempRoot = fs.mkdtempSync(path.join(os.tmpdir(), "a2a-gwenv-test-"));
process.env.ALPHACLAW_ROOT_DIR = kTempRoot;
const kOpenclawDir = path.join(kTempRoot, ".openclaw");
fs.mkdirSync(path.join(kOpenclawDir, ".alphaclaw"), { recursive: true });

const { gatewayEnv } = require("../../lib/server/gateway");
const { createA2aChannelService } = require("../../lib/server/a2a-channel");
const { readEnvFile } = require("../../lib/server/env");
const {
  filterGatewayChildEnv,
  resetGatewayEnvPolicyForTests,
} = require("../../lib/server/gateway-env-policy");

describe("A2A peer token reaches the gateway child env", () => {
  const kVar = "A2A_ITEST_PEER_TOKEN";
  afterEach(() => {
    delete process.env[kVar];
    resetGatewayEnvPolicyForTests();
  });
  afterAll(() => fs.rmSync(kTempRoot, { recursive: true, force: true }));

  it("generate:true writes .env (0600) and gatewayEnv() forwards the variable", async () => {
    fs.writeFileSync(
      path.join(kOpenclawDir, "openclaw.json"),
      JSON.stringify({ channels: { a2a: { enabled: true, peers: {} } } }),
    );
    const logSpy = vi.spyOn(console, "log");
    const service = createA2aChannelService({ openclawDir: kOpenclawDir });
    const result = await service.upsertPeer("itest-peer", { generate: true });
    const stored = readEnvFile().find((v) => v.key === kVar);
    try {
      expect(result.tokenGenerated).toBe(true);
      expect(stored?.value).toMatch(/^[A-Za-z0-9_-]{43}$/);
      expect(fs.statSync(path.join(kTempRoot, ".env")).mode & 0o777).toBe(0o600);
      expect(JSON.stringify(result)).not.toContain(stored.value);
      for (const call of logSpy.mock.calls) {
        expect(call.map(String).join(" ")).not.toContain(stored.value);
      }
      const env = gatewayEnv();
      expect(env[kVar]).toBe(stored.value);
      const config = JSON.parse(fs.readFileSync(path.join(kOpenclawDir, "openclaw.json"), "utf8"));
      expect(config.channels.a2a.peers["itest-peer"]).toEqual({ token: `\${${kVar}}` });
    } finally {
      logSpy.mockRestore();
    }
  });

  it("the allowlist (no passthrough hatch) forwards A2A_*_TOKEN and nothing looser", () => {
    const quiet = { log: vi.fn() };
    const out = filterGatewayChildEnv(
      {
        A2A_CLAUDE_HOST_TOKEN: "a",
        A2A_HERMES_TOKEN: "b",
        A2A_HERMES: "c",
        A2A_HERMES_TOKEN_EXTRA: "d",
        a2a_hermes_token: "e",
        A2A__TOKEN: "f",
      },
      { logger: quiet, hatch: { passthrough: "", unrestricted: false } },
    );
    expect(out).toEqual({ A2A_CLAUDE_HOST_TOKEN: "a", A2A_HERMES_TOKEN: "b" });
  });
});
